[workspace]
members = [
  "http",
  #"httpc",
  #"net",
  #"mqtt_tmp",
  #"rpc_tmp",
  #"nodec",
  "tcp",
  "new_tcp",
  "ws",
  "mqtt",
  "mqtt_proxy",
  "rpc",
  "udp",
  "quic",
  "async_httpc",
  "async_wsc",
]
