[package]
name = "mqtt"
version = "0.1.0"
authors = ["moyy <moyy@yineng.com>"]

[dependencies]
rand = "0.4.2"
mqtt3 = { git = "https://github.com/tekjar/mqtt3" }
string_cache = "0.7.2"
fnv = "1.0.6"
net = {path="../net"}
magnetic = "2.0.0"
pi_base = {path="../../pi_base"}
pi_lib = {path="../../pi_lib"}
