[package]
name = "mqtt"
version = "0.1.0"
authors = ["vmos <vmos@fairblock.io>"]
edition = "2018"

[dependencies]
fnv = "1.0"
futures = "0.3"
mio = "0.6"
mqtt311 = "0.2"
parking_lot = "0.11"
lazy_static = "1.4"
pi_hash = { version = "0.1", features = ["xxhash"] }
tcp = { path = "../tcp" }
ws = { path = "../ws" }
log = "0.4"
pi_atom = "0.1"

[dev-dependencies]
twox-hash = "1.5"