[package]
name = "mqtt"
version = "0.1.0"
authors = ["moyy <moyy@yineng.com>"]

[dependencies]
rustc-serialize = "0.3"
rand = "0.4.2"
mqtt3 = { git = "https://github.com/tekjar/mqtt3" }
fnv = "1.0.6"
net = {path="../net"}
magnetic = "2.0.0"
atom = {path="../../pi_lib/atom"}
time = {path="../../pi_lib/time"}
gray = {path="../../pi_lib/gray"}
compress = { path = "../../pi_lib/compress"}
