[package]
name = "mqtt"
version = "0.1.0"
authors = ["vmos <vmos@fairblock.io>"]
edition = "2018"

[dependencies]
fnv = "1.0"
mqtt311 = "0.2"
hash = { path = "../../pi_lib/hash", features = ["xxhash"] }
atom = { path = "../../pi_lib/atom" }
tcp = { path = "../tcp" }
ws = { path = "../ws" }
