[package]
name = "mqtt"
version = "0.1.0"
authors = ["vmos <vmos@fairblock.io>"]
edition = "2018"

[dependencies]
fnv = "1.0"
mio = "0.6"
mqtt311 = "0.2"
parking_lot = "0.10"
lazy_static = "1.4"
hash = { path = "../../pi_lib/hash", features = ["xxhash"] }
tcp = { path = "../tcp" }
ws = { path = "../ws" }
log = "0.4"
atom = { path = "../../pi_lib/atom" }

[dev-dependencies]
twox-hash = "1.5"
parking_lot = "0.9"