[package]
name = "http"
version = "0.1.0"
authors = ["vmos <vmos@fairblock.io>"]
edition = "2018"

[dependencies]
mio = "0.6"
url = "2.1"
mime = "0.3"
mime_guess = "2.0"
twoway = "0.2"
https = { package = "http", version = "0.2" }
httparse = "1.3"
httpdate = "0.3"
serde_json = "1.0"
futures = "0.3"
parking_lot = "0.10"
crossbeam-channel = "0.4"
regex = "1.3"
base64 = "0.10"
flate2 = "1.0"
bytes = "0.5"
atom = { path = "../../pi_lib/atom" }
path-absolutize = "1.1"
log = "0.4"
env_logger = "0.7"
tcp = { path = "../tcp" }
handler = { path = "../../pi_lib/handler" }
hash = { path = "../../pi_lib/hash", features = ["xxhash"] }
gray = { path = "../../pi_lib/gray" }
file = { path = "../../pi_lib/file" }
adler32 = { path = "../../pi_lib/adler32" }

[dev-dependencies]
route-recognizer = "0.1"
worker = { path = "../../pi_lib/worker" }