[package]
name = "async_httpc"
version = "0.1.0"
authors = ["vmos <vmos@fairblock.io>"]
edition = "2018"

[dependencies]
futures = "0.3"
tokio = { version = "0.2", features = ["rt-core", "rt-threaded"] }
reqwest = { version = "0.10", features = ["native-tls", "rustls-tls", "cookies", "gzip", "json", "socks"] }
bytes = "0.5"
lazy_static = "1.4"
async = { path = "../../pi_lib/async" }

[dev-dependencies]
env_logger = "0.7"
worker = { path = "../../pi_lib/worker" }
tcp = { path = "../../pi_net/tcp" }
http = { path = "../../pi_net/http" }