[package]
name = "httpc"
version = "0.1.0"
authors = ["zuon <dev@dev.com>"]

[dependencies]
reqwest = "0.8.8"
lazy_static = "1.3"
worker = { path = "../../pi_lib/worker" }
atom = { path = "../../pi_lib/atom" }
apm = { path = "../../pi_lib/apm" }