[package]
name = "mqtt_proxy"
version = "0.1.0"
authors = ["vmos <vmos@fairblock.io>"]
edition = "2018"

[dependencies]
pi_handler = "0.1"
tcp = { path = "../tcp" }
mqtt = { path = "../mqtt" }
pi_gray = "0.1"
pi_atom = "0.1"
log = "0.4"

[dev-dependencies]
ws = { path = "../ws" }
