[package]
name = "tcp"
version = "0.1.0"
authors = ["vmos <vmos@fairblock.io>"]

[dependencies]
mio = "0.6"
slab = "0.4"
lazy_static = "1.3"
atom = { path = "../../pi_lib/atom" }
rustls = "0.15"
crossbeam-channel = "0.3"
iovec = "0.1"
apm = { path = "../../pi_lib/apm" }
fnv = "1.0"