[package]
name = "base"
version = "0.1.0"
authors = ["vmos <vmos@fairblock.io>"]
edition = "2018"

[dependencies]
bytes = "0.4"
pi_handler = "0.1"
pi_compress = "0.1"
tcp = { path = "../tcp" }
ws = { path = "../ws" }
mqtt = { path = "../mqtt" }
log = "0.4"