[package]
name = "pi_udp"
version = "0.3.0"
edition = "2021"
description = "pi_udp"
repository = "https://github.com/GaiaWorld/pi_net"
license = "MIT OR Apache-2.0"
keywords = ["pi",  "udp"]

[dependencies]
futures = "0.3"
mio = { version = "0.8", features = ["net", "os-poll"] }
parking_lot = "0.12"
crossbeam-channel = "0.5"
dashmap = "6.1"
bytes = "1.11"
fnv = "1.0"
lazy_static = "1.5"
log = "0.4"
pi_slotmap = "0.1"
pi_hash = "0.1"
pi_async = "0.5"
flume = "0.11"
spin_sleep = "1.3"

[dev-dependencies]
env_logger = "0.11"